spring:
  application:
    name: turbine

server:
  port: 8766

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8740/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

turbine:
  aggregator:
    clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: CONSOLE,GATEWAY  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default") #metadata['cluster']
  # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
  # 2. 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
  # 3. 当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC

